# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: unicode
  database: testapp
  pool: 5
  username: rz_test
  password: revz1ll4
  host: postgres

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
